#server
server:
  port: 8888
#  servlet:
#    context-path: /cwebe

#spring
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cwebe?serverTimezone=UTC
#    url: jdbc:mysql://localhost:3306/cwebe?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
#  resources:
#    static-locations: [
#      "classpath:test1",
#      "classpath:test2"
#    ]
#  mvc:
#    view:
#      prefix: classpath:static
#      suffix: .html
